blog/urls.py
from django.urls import path

from . import views

app_name = "blog"


urlpatterns = [
    path("", views.home_page, name="home"),
    path("detail/<int:post_id>", views.detail, name="detail"),
    path("rating/<int:value>/<int:post_id>", views.set_rating, name="rating"),
    path("search/", views.search, name="search"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(verbose_name="Category name", max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return str(self.name)


class Tag(models.Model):
    name = models.CharField(verbose_name="Tag name", max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return str(self.name)


class Post(models.Model):
    title = models.CharField(verbose_name="Post title", max_length=255)
    body = models.TextField(verbose_name="Post Body")
    author = models.CharField(
        verbose_name="Post Author", default="Admin", max_length=100
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, related_name="posts"
    )
    tag = models.ManyToManyField(Tag)
    views = models.PositiveIntegerField(default=0)
    publish_date = models.DateTimeField(verbose_name="Publish time", auto_now_add=True)
    published = models.BooleanField(default=True)
    on_top = models.BooleanField(default=False)

    def get_avg_rating(self):
        sum_ratings = sum([int(i.value) for i in self.ratings.all()])
        return sum_ratings / self.ratings.all().count()

    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    author = models.CharField(verbose_name="Post Author", max_length=100, blank=False)
    comment = models.TextField(verbose_name="Comment")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return str(self.author)


class Rating(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="ratings")
    value = models.PositiveSmallIntegerField(verbose_name="Post Rating", default=0)

    def __str__(self):
        return str(self.value)

blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Category, Post, Comment, Rating

from .utils import check_read_articles


def home_page(request):
    categories = Category.objects.all()
    posts = Post.objects.all()
    last_comments = Comment.objects.all().order_by("-id")[:10]

    data = {"categories": categories, "posts": posts, "last_comments": last_comments}
    return render(request=request, template_name="index.html", context=data)


def detail(request, post_id):
    category = Category.objects.all()
    post = Post.objects.get(id=post_id)

    if post.id in check_read_articles(request):
        pass
    else:
        check_read_articles(request).append(post.id)
        post.views += 1
        post.save()

    if request.method == "POST":
        name = request.POST.get("name")
        comment = request.POST.get("comment")

        if all([name, comment]):
            Comment.objects.create(author=name, comment=comment, post=post)

    return render(
        request, "detail.html", context={"post": post, "categories": category}
    )


def set_rating(request, value, post_id):
    post = Post.objects.get(id=post_id)
    value = int(value)

    if all([post, value]):
        Rating.objects.create(post=post, value=value)
    return redirect("/")


def category_list(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    posts = Post.objects.filter(category=category)
    last_comments = Comment.objects.all().order_by("-id")[:10]

    return render(
        request,
        "category.html",
        context={"posts": posts, "category": category, "last_comments": last_comments},
    )


def search(request):
    last_comments = Comment.objects.all().order_by("-id")[:10]
    query = request.GET.get("query")
    posts = Post.objects.filter(title__icontains=query)
    return render(
        request,
        "index.html",
        context={"posts": posts, "last_comments": last_comments},
    )

templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>DevBlog</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="./js/snippet.js"></script>
  </head>

  <body>
    <header>
      <!-- place navbar here -->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container">
          <a class="navbar-brand" href="/">DevBlog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact me</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" control-id="ControlID-1" />
              <button class="btn btn-outline-success" type="submit" control-id="ControlID-2">Search</button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <!-- Notifications -->

      <div class="toast position-fixed top-0 end-0 m-1 text-bg-success show" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
          <strong class="me-auto">Success !</strong>
          <small>Message</small>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body d-flex">Hello, world! This is a toast message.</div>
      </div>
      <br />
      <section>
        <div class="container-md">
          <div class="d-flex flex-wrap my-3">
            {% for category in categories %}
              <div class="d-flex flex-wrap mx-3 my-2">
                <button type="button" class="btn btn-primary position-relative">
                  {{ category.name }}
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    {{ category.posts.all.count }}
                    <span class="visually-hidden">unread messages</span>
                  </span>
                </button>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="container-md">
          <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-9">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="content">
                    <h4 class="card-title fw-bold">{{ post.title }}</h4>
                    <p class="card-text">{{ post.body }}</p>
                    <div class="d-flex justify-content-between flex-wrap">
                      <div class="post-rating">
                        <span>Rating:</span>
                        <span class="fs-3 fw-bold text-muted">{{ get_avg_rating }}</span>
                      </div>
                      <div class="post-set-rating">
                        <p class="card-text fs-4">
                          <a href="{% url 'blog:rating' 1 post.id %}"><i class="bi bi-star"></i></a>
                          <a href="{% url 'blog:rating' 2 post.id %}"><i class="bi bi-star"></i></a>
                          <a href="{% url 'blog:rating' 3 post.id %}"><i class="bi bi-star"></i></a>
                          <a href="{% url 'blog:rating' 4 post.id %}"><i class="bi bi-star"></i></a>
                          <a href="{% url 'blog:rating' 5 post.id %}"><i class="bi bi-star"></i></a>
                        </p>
                      </div>
                    </div>

                    <div class="d-flex justify-content-between flex-wrap">
                      <div class="categories">
                        {% for tag in post.tag.all %}
                          <span class="badge rounded-pill text-bg-secondary">{{ tag.name }}</span>
                        {% endfor %}
                      </div>
                      <div class="action">
                        <span class="badge bg-primary rounded-pill">
                          <i class="bi bi-list-stars"></i>
                          {{ post.ratings.all.count }}
                        </span>
                        <span class="badge bg-primary rounded-pill">
                          <i class="bi bi-eye"></i>
                          {{ post.views }}
                        </span>
                        <span class="badge bg-primary rounded-pill">
                          <i class="bi bi-chat-square-text"></i>
                          {{ post.comment.all.count }}
                        </span>
                      </div>
                    </div>

                    <br />
                  </div>
                </div>
              </div>
              <div class="comments">
                <div class="row gap-3">
                  <div class="col-sm-12">
                    {% for comment in post.comments.all %}
                      <div class="card">
                        <div class="card-header">{{ comment.author }}</div>
                        <div class="card-body p-2">
                          <p>{{ comment.comment }}</p>
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                  <div class="col-sm-12">
                    <span class="fs-5 fw-semibold">Your minds...</span>
                    <form method="POST" action="">
                      {% csrf_token %}
                      <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Name</label>
                        <input type="text" name="name" class="form-control" id="exampleFormControlInput1" placeholder="John Doe" />
                      </div>
                      <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Comment text</label>
                        <textarea class="form-control" name="comment" id="exampleFormControlTextarea1" rows="3"></textarea>
                      </div>
                      <button type="submit" class="btn btn-outline-success">Comment</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-none col-md-12 col-lg-3">
              <span class="fs-5 fw-semibold">Related posts</span>
              <ol class="list-group list-group-numbered">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">Subheading dadas adasda as af afas a fafase</div>
                  </div>
                  <span class="badge bg-primary rounded-pill">
                    <i class="bi bi-eye"></i>
                    14
                  </span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">Subheading</div>Content for list item
                  </div>
                  <span class="badge bg-primary rounded-pill">14</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">Subheading</div>Content for list item
                  </div>
                  <span class="badge bg-primary rounded-pill">14</span>
                </li>
              </ol>
            </div>
          </div>
        </div>
      </section>
    </main>
    <footer class="footer mt-auto text-white-50 bg-dark">
      <!-- place footer here -->
      <div class="container">
        <div class="row my-5">
          <div class="col-12">
            <nav style="--bs-breadcrumb-divider: '|';" aria-label="breadcrumb" class="py-3">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/" class="text-decoration-none">Home</a>
                </li>
                <li class="breadcrumb-item" aria-current="page">
                  <a href="#" class="text-decoration-none">Contact me</a>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>DevBlog</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="./js/snippet.js"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container">
          <a class="navbar-brand" href="/">DevBlog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact me</a>
              </li>
            </ul>
            <form class="d-flex" role="search" action="{% url 'blog:search' %}" method="get">
              <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" control-id="ControlID-1" />
              <button class="btn btn-outline-success" type="submit" control-id="ControlID-2">Search</button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="toast position-fixed top-0 end-0 m-1 text-bg-success show" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
          <strong class="me-auto">Success !</strong>
          <small>Message</small>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body d-flex">Hello, world! This is a toast message.</div>
      </div>
      <br />
      <section>
        <div class="container-md">
          <div class="d-flex flex-wrap my-3">
            {% for category in categories %}
              <div class="d-flex flex-wrap mx-3 my-2">
                <button type="button" class="btn btn-primary position-relative">
                  {{ category.name }}
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    {{ category.posts.all.count }}
                    <span class="visually-hidden">unread messages</span>
                  </span>
                </button>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="container-md">
          <div class="row">
            <div class="col-sm-12 col-md-9">
              {% for post in posts %}
                <div class="card mb-3">
                  <div class="card-body">
                    <div class="content">
                      <a href="{% url 'blog:detail' post.id %}" class="text-decoration-none"><h4 class="card-title fw-bold">{{ post.title }}</h4></a>
                      <p class="card-text">{{ post.body|truncatewords:'25' }}</p>

                      {% for tag in post.tag.all %}
                        <span class="badge rounded-pill text-bg-secondary">{{ tag.name }}</span>
                      {% endfor %}
                      <br />
                      <span class="badge bg-primary rounded-pill">
                        <i class="bi bi-list-stars"></i>
                        {{ post.ratings.all.count }}
                      </span>
                      <span class="badge bg-primary rounded-pill">
                        <i class="bi bi-eye"></i>
                        {{ post.views }}
                      </span>
                      <span class="badge bg-primary rounded-pill">
                        <i class="bi bi-chat-square-text"></i>
                        {{ post.comments.all.count }}
                      </span>
                      <a href="#" class="btn btn-secondary float-end">Read</a>
                    </div>
                  </div>
                </div>
              {% endfor %}
              <nav aria-label="...">
                <ul class="pagination">
                  <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">1</a>
                  </li>
                  <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">2</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">3</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                  </li>
                </ul>
              </nav>
            </div>
            <div class="col-sm-none col-md-3">
              <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary" style="width: 380px;">
                <a href="/" class="d-flex align-items-center flex-shrink-0 p-3 link-body-emphasis text-decoration-none border-bottom">
                  <svg class="bi pe-none me-2" width="30" height="24">
                    <use xlink:href="#bootstrap"></use>
                  </svg>
                  <span class="fs-5 fw-semibold">Last comments</span>
                </a>
                <div class="list-group list-group-flush border-bottom scrollarea">
                  {% for comment in last_comments %}
                    <a href="{% url 'blog:detail' comment.post.id %}" class="list-group-item list-group-item-action py-3 lh-sm">
                      <div class="d-flex w-100 align-items-center justify-content-between">
                        <strong class="mb-1">{{ comment.post.title }}</strong>
                      </div>
                      <div class="col-10 mb-1 small">{{ comment.comment }}</div>
                    </a>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
    <footer class="footer mt-auto text-white-50 bg-dark">
      <div class="container">
        <div class="row my-5">
          <div class="col-12">
            <nav style="--bs-breadcrumb-divider: '|';" aria-label="breadcrumb" class="py-3">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/" class="text-decoration-none">Home</a>
                </li>
                <li class="breadcrumb-item" aria-current="page">
                  <a href="#" class="text-decoration-none">Contact me</a>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>